# -*- coding: utf-8 -*-
# Deployment settings for HelloMarm.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Applications/Marmalade.app/Contents/s3e/makefile_builder/mkb.py', '/Users/dean/devel/marmalade/HelloMarm/HelloMarm.mkb', '--deploy-only', '--hub-data', '/Users/dean/devel/marmalade/HelloMarm/project_HelloMarm/mkb-scons.txt', '--buildenv=SCONS']
mkb = '/Users/dean/devel/marmalade/HelloMarm/HelloMarm.mkb'
mkf = ['/Applications/Marmalade.app/Contents/modules/iwutil/iwutil.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libjpeg/libjpeg.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libpng/libpng.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/zlib/zlib.mkf', '/Applications/Marmalade.app/Contents/modules/iwgx/iwgx.mkf', '/Applications/Marmalade.app/Contents/modules/iwgl/iwgl.mkf', '/Applications/Marmalade.app/Contents/modules/iwgeom/iwgeom.mkf', '/Applications/Marmalade.app/Contents/modules/iwresmanager/iwresmanager.mkf', '/Applications/Marmalade.app/Contents/extensions/PVRTexTool/PVRTexTool.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/dean/devel/marmalade/HelloMarm/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'HelloMarm'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'HelloMarm'
    long_caption = 'HelloMarm'
    version = [0, 0, 1]
    config = ['/Users/dean/devel/marmalade/HelloMarm/data/app.icf']
    data_dir = '/Users/dean/devel/marmalade/HelloMarm/data'
    iphone_link_lib = []
    osx_ext_dll = ['/Applications/Marmalade.app/Contents/extensions/PVRTexTool/lib/osx/libPVRTexTool.dylib']
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['/Applications/Marmalade.app/Contents/extensions/PVRTexTool/lib/win32/PVRTexTool.dll']
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws81_ext_sdk_ref_file = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    android_external_jars = []
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = []
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = []
    android_so = []
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_x86/debug/HelloMarm.so',
                   'release' : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_x86/release/HelloMarm.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_x86/debug/HelloMarm.s86',
                   'release' : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_x86/release/HelloMarm.s86',
                 },
         'x86' : {
                   'debug'   : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_x86/debug/HelloMarm.s86',
                   'release' : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_x86/release/HelloMarm.s86',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_x86/debug/HelloMarm.so',
                   'release' : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_x86/release/HelloMarm.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_arm/debug/HelloMarm.s3e',
                   'release' : r'/Users/dean/devel/marmalade/HelloMarm/build_hellomarm_scons_arm/release/HelloMarm.s3e',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
